name: test-workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install coverage
      - name: Test with unittest
        run: | 
          python -m unittest -v
          coverage run -m unittest
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1