name: test-workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install pytest
      - name: Test with pytest
        run: | 
          pytest ./tests/TestBishop.py
          pytest ./tests/TestBoard.py
          pytest ./tests/TestChessEngine.py
          pytest ./tests/TestKing.py
          pytest ./tests/TestKnight.py
          pytest ./tests/TestPawn.py
          pytest ./tests/TestQueen.py
          pytest ./tests/TestRook.py 
